name: Code Review
on:
  pull_request:
    branches:
      - main
      - int
permissions:
  contents: read

jobs:
  code-review:
    name: Code Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          egress-policy: audit

      - name: Code Review
        uses: docker://ghcr.io/step-security/code-reviewer/int:latest
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
